exclude:
  - Makefile
  - "*.zip"
  - "*.dot"
  - src
  - old

defaults:
  -
    scope:
      path: "" # all files in the project
    values:
      layout: "default"

kramdown:
  parse_block_html: true
  toc_levels: "1"
  math_engine: mathjax

mathjax_url: 'https://cdn.jsdelivr.net/npm/mathjax@3'
