title: Static Analysis and Program Verification
theme: minima

exclude:
  - Makefile
  - "*.zip"
  - "*.dot"
  - src
  - old
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: "" # all files in the project
    values:
      layout: "page"

kramdown:
  parse_block_html: true
  toc_levels: "1"
  math_engine: mathjax

mathjax_url: 'https://cdn.jsdelivr.net/npm/mathjax@3'
custom_font: true