title: Introduction to Program Verification
theme: minima

exclude:
  - Makefile
  - "*.zip"
  - "*.dot"
  - "*.agdai"
  - "*.sh"
  - old
  - src
  - "*.pdf"
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - TODO.md

defaults:
  -
    scope:
      path: "" # all files in the project
    values:
      layout: "page"

kramdown:
  parse_block_html: true
  toc_levels: "1"
  math_engine: mathjax

mathjax_url: 'https://cdn.jsdelivr.net/npm/mathjax@3'
custom_font: true
